// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: usher/v1/usher.proto

// Package usher.v1 is the wire between the usher CLI and the usher daemon.
//
// The daemon owns the route table and the Caddy config; the CLI only asks it
// for changes. That is why `usher up` needs no sudo and why there is no shared
// directory of config fragments for the two halves to disagree about.

package usherv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Adapter names the kind of thing a route points at. The CLI does all the
// adapter-specific work before it ever calls the daemon; the daemon stores the
// adapter only so `usher urls` and `usher down` know which one owns a route.
type Adapter int32

const (
	Adapter_ADAPTER_UNSPECIFIED Adapter = 0
	// A literal ip:port the user supplied. No machine to attach to.
	Adapter_ADAPTER_STATIC Adapter = 1
	// A Docker Sandbox microVM, reached through a published host port.
	Adapter_ADAPTER_SBX Adapter = 2
	// An OrbStack VM, reached by name at <machine>.orb.local.
	Adapter_ADAPTER_ORB Adapter = 3
	// A running container, reached through a port it already publishes.
	Adapter_ADAPTER_DOCKER Adapter = 4
)

// Enum value maps for Adapter.
var (
	Adapter_name = map[int32]string{
		0: "ADAPTER_UNSPECIFIED",
		1: "ADAPTER_STATIC",
		2: "ADAPTER_SBX",
		3: "ADAPTER_ORB",
		4: "ADAPTER_DOCKER",
	}
	Adapter_value = map[string]int32{
		"ADAPTER_UNSPECIFIED": 0,
		"ADAPTER_STATIC":      1,
		"ADAPTER_SBX":         2,
		"ADAPTER_ORB":         3,
		"ADAPTER_DOCKER":      4,
	}
)

func (x Adapter) Enum() *Adapter {
	p := new(Adapter)
	*p = x
	return p
}

func (x Adapter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Adapter) Descriptor() protoreflect.EnumDescriptor {
	return file_usher_v1_usher_proto_enumTypes[0].Descriptor()
}

func (Adapter) Type() protoreflect.EnumType {
	return &file_usher_v1_usher_proto_enumTypes[0]
}

func (x Adapter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Adapter.Descriptor instead.
func (Adapter) EnumDescriptor() ([]byte, []int) {
	return file_usher_v1_usher_proto_rawDescGZIP(), []int{0}
}

// Route is one hostname reachable at https://<host>.<domain>, forwarding to
// upstream. A single machine can have many Routes (e.g. one per tenant in a
// multi-tenant app that switches on Host), which is why the machine name is
// carried on the route rather than being the route's key.
type Route struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Host    string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Adapter Adapter                `protobuf:"varint,2,opt,name=adapter,proto3,enum=usher.v1.Adapter" json:"adapter,omitempty"`
	// machine is the sandbox, VM, or container name. Empty for static routes.
	Machine string `protobuf:"bytes,3,opt,name=machine,proto3" json:"machine,omitempty"`
	// machine_port is the port the app listens on inside the machine.
	MachinePort uint32 `protobuf:"varint,4,opt,name=machine_port,json=machinePort,proto3" json:"machine_port,omitempty"`
	// upstream is exactly what Caddy dials, e.g. "127.0.0.1:31847" or
	// "canvas.orb.local:3000".
	Upstream string `protobuf:"bytes,5,opt,name=upstream,proto3" json:"upstream,omitempty"`
	// host_port is non-zero only when a host port is involved. Routes that
	// share an (adapter, machine, machine_port) triple share a host_port too,
	// so a multi-tenant machine doesn't get the same port published twice.
	HostPort      uint32 `protobuf:"varint,6,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_usher_v1_usher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_usher_v1_usher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_usher_v1_usher_proto_rawDescGZIP(), []int{0}
}

func (x *Route) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Route) GetAdapter() Adapter {
	if x != nil {
		return x.Adapter
	}
	return Adapter_ADAPTER_UNSPECIFIED
}

func (x *Route) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *Route) GetMachinePort() uint32 {
	if x != nil {
		return x.MachinePort
	}
	return 0
}

func (x *Route) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *Route) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_usher_v1_usher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usher_v1_usher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_usher_v1_usher_proto_rawDescGZIP(), []int{1}
}

type ListRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_usher_v1_usher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usher_v1_usher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_usher_v1_usher_proto_rawDescGZIP(), []int{2}
}

func (x *ListRoutesResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

// UpsertRouteRequest asks the daemon to route host somewhere.
//
// The caller fills in the dial target when it knows it. Static and orb routes
// set upstream; the docker adapter sets host_port, having found a port the
// container already publishes. The sbx adapter sets neither, because only the
// daemon knows which ports its other routes already hold.
type UpsertRouteRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Host        string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Adapter     Adapter                `protobuf:"varint,2,opt,name=adapter,proto3,enum=usher.v1.Adapter" json:"adapter,omitempty"`
	Machine     string                 `protobuf:"bytes,3,opt,name=machine,proto3" json:"machine,omitempty"`
	MachinePort uint32                 `protobuf:"varint,4,opt,name=machine_port,json=machinePort,proto3" json:"machine_port,omitempty"`
	// upstream, when set, is used verbatim.
	Upstream string `protobuf:"bytes,5,opt,name=upstream,proto3" json:"upstream,omitempty"`
	// host_port, when set and upstream is empty, becomes 127.0.0.1:<host_port>.
	HostPort      uint32 `protobuf:"varint,6,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRouteRequest) Reset() {
	*x = UpsertRouteRequest{}
	mi := &file_usher_v1_usher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRouteRequest) ProtoMessage() {}

func (x *UpsertRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usher_v1_usher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRouteRequest.ProtoReflect.Descriptor instead.
func (*UpsertRouteRequest) Descriptor() ([]byte, []int) {
	return file_usher_v1_usher_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertRouteRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *UpsertRouteRequest) GetAdapter() Adapter {
	if x != nil {
		return x.Adapter
	}
	return Adapter_ADAPTER_UNSPECIFIED
}

func (x *UpsertRouteRequest) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *UpsertRouteRequest) GetMachinePort() uint32 {
	if x != nil {
		return x.MachinePort
	}
	return 0
}

func (x *UpsertRouteRequest) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *UpsertRouteRequest) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

type UpsertRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRouteResponse) Reset() {
	*x = UpsertRouteResponse{}
	mi := &file_usher_v1_usher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRouteResponse) ProtoMessage() {}

func (x *UpsertRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usher_v1_usher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRouteResponse.ProtoReflect.Descriptor instead.
func (*UpsertRouteResponse) Descriptor() ([]byte, []int) {
	return file_usher_v1_usher_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type RemoveRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRouteRequest) Reset() {
	*x = RemoveRouteRequest{}
	mi := &file_usher_v1_usher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRouteRequest) ProtoMessage() {}

func (x *RemoveRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usher_v1_usher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRouteRequest.ProtoReflect.Descriptor instead.
func (*RemoveRouteRequest) Descriptor() ([]byte, []int) {
	return file_usher_v1_usher_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveRouteRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type RemoveRouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// route is the route that was removed, unset if the host had no route.
	Route         *Route `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRouteResponse) Reset() {
	*x = RemoveRouteResponse{}
	mi := &file_usher_v1_usher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRouteResponse) ProtoMessage() {}

func (x *RemoveRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usher_v1_usher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRouteResponse.ProtoReflect.Descriptor instead.
func (*RemoveRouteResponse) Descriptor() ([]byte, []int) {
	return file_usher_v1_usher_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

// RemoveMachineRoutesRequest drops every route for a machine at once, e.g.
// when the machine itself is being destroyed.
type RemoveMachineRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Adapter       Adapter                `protobuf:"varint,1,opt,name=adapter,proto3,enum=usher.v1.Adapter" json:"adapter,omitempty"`
	Machine       string                 `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMachineRoutesRequest) Reset() {
	*x = RemoveMachineRoutesRequest{}
	mi := &file_usher_v1_usher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMachineRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMachineRoutesRequest) ProtoMessage() {}

func (x *RemoveMachineRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usher_v1_usher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMachineRoutesRequest.ProtoReflect.Descriptor instead.
func (*RemoveMachineRoutesRequest) Descriptor() ([]byte, []int) {
	return file_usher_v1_usher_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveMachineRoutesRequest) GetAdapter() Adapter {
	if x != nil {
		return x.Adapter
	}
	return Adapter_ADAPTER_UNSPECIFIED
}

func (x *RemoveMachineRoutesRequest) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

type RemoveMachineRoutesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// routes are the routes that were removed.
	Routes        []*Route `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMachineRoutesResponse) Reset() {
	*x = RemoveMachineRoutesResponse{}
	mi := &file_usher_v1_usher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMachineRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMachineRoutesResponse) ProtoMessage() {}

func (x *RemoveMachineRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usher_v1_usher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMachineRoutesResponse.ProtoReflect.Descriptor instead.
func (*RemoveMachineRoutesResponse) Descriptor() ([]byte, []int) {
	return file_usher_v1_usher_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveMachineRoutesResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_usher_v1_usher_proto protoreflect.FileDescriptor

const file_usher_v1_usher_proto_rawDesc = "" +
	"\n" +
	"\x14usher/v1/usher.proto\x12\busher.v1\"\xbe\x01\n" +
	"\x05Route\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12+\n" +
	"\aadapter\x18\x02 \x01(\x0e2\x11.usher.v1.AdapterR\aadapter\x12\x18\n" +
	"\amachine\x18\x03 \x01(\tR\amachine\x12!\n" +
	"\fmachine_port\x18\x04 \x01(\rR\vmachinePort\x12\x1a\n" +
	"\bupstream\x18\x05 \x01(\tR\bupstream\x12\x1b\n" +
	"\thost_port\x18\x06 \x01(\rR\bhostPort\"\x13\n" +
	"\x11ListRoutesRequest\"=\n" +
	"\x12ListRoutesResponse\x12'\n" +
	"\x06routes\x18\x01 \x03(\v2\x0f.usher.v1.RouteR\x06routes\"\xcb\x01\n" +
	"\x12UpsertRouteRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12+\n" +
	"\aadapter\x18\x02 \x01(\x0e2\x11.usher.v1.AdapterR\aadapter\x12\x18\n" +
	"\amachine\x18\x03 \x01(\tR\amachine\x12!\n" +
	"\fmachine_port\x18\x04 \x01(\rR\vmachinePort\x12\x1a\n" +
	"\bupstream\x18\x05 \x01(\tR\bupstream\x12\x1b\n" +
	"\thost_port\x18\x06 \x01(\rR\bhostPort\"<\n" +
	"\x13UpsertRouteResponse\x12%\n" +
	"\x05route\x18\x01 \x01(\v2\x0f.usher.v1.RouteR\x05route\"(\n" +
	"\x12RemoveRouteRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"<\n" +
	"\x13RemoveRouteResponse\x12%\n" +
	"\x05route\x18\x01 \x01(\v2\x0f.usher.v1.RouteR\x05route\"c\n" +
	"\x1aRemoveMachineRoutesRequest\x12+\n" +
	"\aadapter\x18\x01 \x01(\x0e2\x11.usher.v1.AdapterR\aadapter\x12\x18\n" +
	"\amachine\x18\x02 \x01(\tR\amachine\"F\n" +
	"\x1bRemoveMachineRoutesResponse\x12'\n" +
	"\x06routes\x18\x01 \x03(\v2\x0f.usher.v1.RouteR\x06routes*l\n" +
	"\aAdapter\x12\x17\n" +
	"\x13ADAPTER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eADAPTER_STATIC\x10\x01\x12\x0f\n" +
	"\vADAPTER_SBX\x10\x02\x12\x0f\n" +
	"\vADAPTER_ORB\x10\x03\x12\x12\n" +
	"\x0eADAPTER_DOCKER\x10\x042\xd3\x02\n" +
	"\fRouteService\x12G\n" +
	"\n" +
	"ListRoutes\x12\x1b.usher.v1.ListRoutesRequest\x1a\x1c.usher.v1.ListRoutesResponse\x12J\n" +
	"\vUpsertRoute\x12\x1c.usher.v1.UpsertRouteRequest\x1a\x1d.usher.v1.UpsertRouteResponse\x12J\n" +
	"\vRemoveRoute\x12\x1c.usher.v1.RemoveRouteRequest\x1a\x1d.usher.v1.RemoveRouteResponse\x12b\n" +
	"\x13RemoveMachineRoutes\x12$.usher.v1.RemoveMachineRoutesRequest\x1a%.usher.v1.RemoveMachineRoutesResponseB8Z6github.com/hawkbawk/usher/internal/api/usherv1;usherv1b\x06proto3"

var (
	file_usher_v1_usher_proto_rawDescOnce sync.Once
	file_usher_v1_usher_proto_rawDescData []byte
)

func file_usher_v1_usher_proto_rawDescGZIP() []byte {
	file_usher_v1_usher_proto_rawDescOnce.Do(func() {
		file_usher_v1_usher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usher_v1_usher_proto_rawDesc), len(file_usher_v1_usher_proto_rawDesc)))
	})
	return file_usher_v1_usher_proto_rawDescData
}

var file_usher_v1_usher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_usher_v1_usher_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_usher_v1_usher_proto_goTypes = []any{
	(Adapter)(0),                        // 0: usher.v1.Adapter
	(*Route)(nil),                       // 1: usher.v1.Route
	(*ListRoutesRequest)(nil),           // 2: usher.v1.ListRoutesRequest
	(*ListRoutesResponse)(nil),          // 3: usher.v1.ListRoutesResponse
	(*UpsertRouteRequest)(nil),          // 4: usher.v1.UpsertRouteRequest
	(*UpsertRouteResponse)(nil),         // 5: usher.v1.UpsertRouteResponse
	(*RemoveRouteRequest)(nil),          // 6: usher.v1.RemoveRouteRequest
	(*RemoveRouteResponse)(nil),         // 7: usher.v1.RemoveRouteResponse
	(*RemoveMachineRoutesRequest)(nil),  // 8: usher.v1.RemoveMachineRoutesRequest
	(*RemoveMachineRoutesResponse)(nil), // 9: usher.v1.RemoveMachineRoutesResponse
}
var file_usher_v1_usher_proto_depIdxs = []int32{
	0,  // 0: usher.v1.Route.adapter:type_name -> usher.v1.Adapter
	1,  // 1: usher.v1.ListRoutesResponse.routes:type_name -> usher.v1.Route
	0,  // 2: usher.v1.UpsertRouteRequest.adapter:type_name -> usher.v1.Adapter
	1,  // 3: usher.v1.UpsertRouteResponse.route:type_name -> usher.v1.Route
	1,  // 4: usher.v1.RemoveRouteResponse.route:type_name -> usher.v1.Route
	0,  // 5: usher.v1.RemoveMachineRoutesRequest.adapter:type_name -> usher.v1.Adapter
	1,  // 6: usher.v1.RemoveMachineRoutesResponse.routes:type_name -> usher.v1.Route
	2,  // 7: usher.v1.RouteService.ListRoutes:input_type -> usher.v1.ListRoutesRequest
	4,  // 8: usher.v1.RouteService.UpsertRoute:input_type -> usher.v1.UpsertRouteRequest
	6,  // 9: usher.v1.RouteService.RemoveRoute:input_type -> usher.v1.RemoveRouteRequest
	8,  // 10: usher.v1.RouteService.RemoveMachineRoutes:input_type -> usher.v1.RemoveMachineRoutesRequest
	3,  // 11: usher.v1.RouteService.ListRoutes:output_type -> usher.v1.ListRoutesResponse
	5,  // 12: usher.v1.RouteService.UpsertRoute:output_type -> usher.v1.UpsertRouteResponse
	7,  // 13: usher.v1.RouteService.RemoveRoute:output_type -> usher.v1.RemoveRouteResponse
	9,  // 14: usher.v1.RouteService.RemoveMachineRoutes:output_type -> usher.v1.RemoveMachineRoutesResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_usher_v1_usher_proto_init() }
func file_usher_v1_usher_proto_init() {
	if File_usher_v1_usher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usher_v1_usher_proto_rawDesc), len(file_usher_v1_usher_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usher_v1_usher_proto_goTypes,
		DependencyIndexes: file_usher_v1_usher_proto_depIdxs,
		EnumInfos:         file_usher_v1_usher_proto_enumTypes,
		MessageInfos:      file_usher_v1_usher_proto_msgTypes,
	}.Build()
	File_usher_v1_usher_proto = out.File
	file_usher_v1_usher_proto_goTypes = nil
	file_usher_v1_usher_proto_depIdxs = nil
}
