// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: esb/v1/esb.proto

// Package esb.v1 is the wire between the esb CLI and the esb daemon.
//
// The daemon owns the route table and the Caddy config; the CLI only asks it
// for changes. That is why `esb up` needs no sudo and why there is no shared
// directory of config fragments for the two halves to disagree about.

package esbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Route is one sandbox reachable at https://<label>.<domain>.
type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Label string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// host_port is bound on 127.0.0.1 by the sandbox runtime.
	HostPort uint32 `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	// sandbox_port is the port the app listens on inside the microVM.
	SandboxPort   uint32 `protobuf:"varint,3,opt,name=sandbox_port,json=sandboxPort,proto3" json:"sandbox_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_esb_v1_esb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_esb_v1_esb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_esb_v1_esb_proto_rawDescGZIP(), []int{0}
}

func (x *Route) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Route) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *Route) GetSandboxPort() uint32 {
	if x != nil {
		return x.SandboxPort
	}
	return 0
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_esb_v1_esb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_esb_v1_esb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_esb_v1_esb_proto_rawDescGZIP(), []int{1}
}

type ListRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_esb_v1_esb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_esb_v1_esb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_esb_v1_esb_proto_rawDescGZIP(), []int{2}
}

func (x *ListRoutesResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

// UpsertRouteRequest asks the daemon to route a label. The daemon picks the
// host port, because only it knows which ports its other routes already hold.
type UpsertRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	SandboxPort   uint32                 `protobuf:"varint,2,opt,name=sandbox_port,json=sandboxPort,proto3" json:"sandbox_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRouteRequest) Reset() {
	*x = UpsertRouteRequest{}
	mi := &file_esb_v1_esb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRouteRequest) ProtoMessage() {}

func (x *UpsertRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_esb_v1_esb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRouteRequest.ProtoReflect.Descriptor instead.
func (*UpsertRouteRequest) Descriptor() ([]byte, []int) {
	return file_esb_v1_esb_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertRouteRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UpsertRouteRequest) GetSandboxPort() uint32 {
	if x != nil {
		return x.SandboxPort
	}
	return 0
}

type UpsertRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRouteResponse) Reset() {
	*x = UpsertRouteResponse{}
	mi := &file_esb_v1_esb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRouteResponse) ProtoMessage() {}

func (x *UpsertRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_esb_v1_esb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRouteResponse.ProtoReflect.Descriptor instead.
func (*UpsertRouteResponse) Descriptor() ([]byte, []int) {
	return file_esb_v1_esb_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type RemoveRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRouteRequest) Reset() {
	*x = RemoveRouteRequest{}
	mi := &file_esb_v1_esb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRouteRequest) ProtoMessage() {}

func (x *RemoveRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_esb_v1_esb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRouteRequest.ProtoReflect.Descriptor instead.
func (*RemoveRouteRequest) Descriptor() ([]byte, []int) {
	return file_esb_v1_esb_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveRouteRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type RemoveRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRouteResponse) Reset() {
	*x = RemoveRouteResponse{}
	mi := &file_esb_v1_esb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRouteResponse) ProtoMessage() {}

func (x *RemoveRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_esb_v1_esb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRouteResponse.ProtoReflect.Descriptor instead.
func (*RemoveRouteResponse) Descriptor() ([]byte, []int) {
	return file_esb_v1_esb_proto_rawDescGZIP(), []int{6}
}

var File_esb_v1_esb_proto protoreflect.FileDescriptor

const file_esb_v1_esb_proto_rawDesc = "" +
	"\n" +
	"\x10esb/v1/esb.proto\x12\x06esb.v1\"]\n" +
	"\x05Route\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\rR\bhostPort\x12!\n" +
	"\fsandbox_port\x18\x03 \x01(\rR\vsandboxPort\"\x13\n" +
	"\x11ListRoutesRequest\";\n" +
	"\x12ListRoutesResponse\x12%\n" +
	"\x06routes\x18\x01 \x03(\v2\r.esb.v1.RouteR\x06routes\"M\n" +
	"\x12UpsertRouteRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12!\n" +
	"\fsandbox_port\x18\x02 \x01(\rR\vsandboxPort\":\n" +
	"\x13UpsertRouteResponse\x12#\n" +
	"\x05route\x18\x01 \x01(\v2\r.esb.v1.RouteR\x05route\"*\n" +
	"\x12RemoveRouteRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"\x15\n" +
	"\x13RemoveRouteResponse2\xe3\x01\n" +
	"\fRouteService\x12C\n" +
	"\n" +
	"ListRoutes\x12\x19.esb.v1.ListRoutesRequest\x1a\x1a.esb.v1.ListRoutesResponse\x12F\n" +
	"\vUpsertRoute\x12\x1a.esb.v1.UpsertRouteRequest\x1a\x1b.esb.v1.UpsertRouteResponse\x12F\n" +
	"\vRemoveRoute\x12\x1a.esb.v1.RemoveRouteRequest\x1a\x1b.esb.v1.RemoveRouteResponseB2Z0github.com/hawkbawk/esb/internal/api/esbv1;esbv1b\x06proto3"

var (
	file_esb_v1_esb_proto_rawDescOnce sync.Once
	file_esb_v1_esb_proto_rawDescData []byte
)

func file_esb_v1_esb_proto_rawDescGZIP() []byte {
	file_esb_v1_esb_proto_rawDescOnce.Do(func() {
		file_esb_v1_esb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_esb_v1_esb_proto_rawDesc), len(file_esb_v1_esb_proto_rawDesc)))
	})
	return file_esb_v1_esb_proto_rawDescData
}

var file_esb_v1_esb_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_esb_v1_esb_proto_goTypes = []any{
	(*Route)(nil),               // 0: esb.v1.Route
	(*ListRoutesRequest)(nil),   // 1: esb.v1.ListRoutesRequest
	(*ListRoutesResponse)(nil),  // 2: esb.v1.ListRoutesResponse
	(*UpsertRouteRequest)(nil),  // 3: esb.v1.UpsertRouteRequest
	(*UpsertRouteResponse)(nil), // 4: esb.v1.UpsertRouteResponse
	(*RemoveRouteRequest)(nil),  // 5: esb.v1.RemoveRouteRequest
	(*RemoveRouteResponse)(nil), // 6: esb.v1.RemoveRouteResponse
}
var file_esb_v1_esb_proto_depIdxs = []int32{
	0, // 0: esb.v1.ListRoutesResponse.routes:type_name -> esb.v1.Route
	0, // 1: esb.v1.UpsertRouteResponse.route:type_name -> esb.v1.Route
	1, // 2: esb.v1.RouteService.ListRoutes:input_type -> esb.v1.ListRoutesRequest
	3, // 3: esb.v1.RouteService.UpsertRoute:input_type -> esb.v1.UpsertRouteRequest
	5, // 4: esb.v1.RouteService.RemoveRoute:input_type -> esb.v1.RemoveRouteRequest
	2, // 5: esb.v1.RouteService.ListRoutes:output_type -> esb.v1.ListRoutesResponse
	4, // 6: esb.v1.RouteService.UpsertRoute:output_type -> esb.v1.UpsertRouteResponse
	6, // 7: esb.v1.RouteService.RemoveRoute:output_type -> esb.v1.RemoveRouteResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_esb_v1_esb_proto_init() }
func file_esb_v1_esb_proto_init() {
	if File_esb_v1_esb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_esb_v1_esb_proto_rawDesc), len(file_esb_v1_esb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_esb_v1_esb_proto_goTypes,
		DependencyIndexes: file_esb_v1_esb_proto_depIdxs,
		MessageInfos:      file_esb_v1_esb_proto_msgTypes,
	}.Build()
	File_esb_v1_esb_proto = out.File
	file_esb_v1_esb_proto_goTypes = nil
	file_esb_v1_esb_proto_depIdxs = nil
}
